version: '3.4'

services:
  
  dailytrends.web:
    container_name: dailytrends.web
    depends_on:
      - dailytrends.api
    ports:
      - "4200:80"
  
  dailytrends.api:
    container_name: dailytrends.api
    depends_on: 
    - dailytrends.db
    ports:
      - "8080:8080"
    environment:
      - MONGO_CONNECTION_STRING=mongodb://dailytrends.db:27017
      - MONGO_DAILYTRENDS_DB=daily-trends
      - MONGO_FEEDS_COLLECTION_NAME=feeds
      - API_PORT=8080
      - UPDATE_ALL_FEEDS_CRON_TIME_JOB=00 00 6 * * *
  
  dailytrends.db:
    container_name: dailytrends.db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db